config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
        path('', include('notes.urls')),
        path('account/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),
        path('admin/', admin.site.urls),
        path('contact/', include('contact.urls'))
    ]

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + debug_toolbar_urls() 



  

notes/urls.py
from django.urls import path
from .views import NotesIndexView, NoteUpdateView, delete_note

app_name = 'notes'

urlpatterns = [
    path('', NotesIndexView.as_view(), name='index'),
    path('note/update/<uuid:pk>/', NoteUpdateView.as_view(), name='note-update'),
    path('note/delete/<uuid:pk>/', delete_note, name='note-delete'),
    ]

notes/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
                         
from tools.models import TimeStampedModel
from tools.constants import STATUS_CHOICES, SUBJECT_CHOICES, COMMUNICATION_METHODS

from contact.models import Contact
from .manager import NoteManager


User = get_user_model()

class Note(TimeStampedModel):       
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Χρήστης', null=True, blank=True)
    contact = models.ForeignKey(Contact, on_delete=models.PROTECT, related_name='notes',
                                  verbose_name='Επαφή')
    method = models.CharField('Επικοινωνία', max_length=20,
                               choices=COMMUNICATION_METHODS, default='Γραφείο')
    subject = models.CharField('Θεμα', max_length=255, choices=SUBJECT_CHOICES, 
                               default='Άλλο')
    summary = models.TextField('Περιληψη', blank=True, null=True)
    status = models.CharField('Κατασταση', max_length=20, choices=STATUS_CHOICES,
                               default='Ανοιχτό')
    completed = models.BooleanField('ολοκληρωθηκε', default=False)
    shortcode = models.CharField(max_length=10, unique=True, blank=True, null=True)

    objects = models.Manager() 
    lookfors = NoteManager()   

    class Meta:
        verbose_name = 'Σημειωση'
        verbose_name_plural = 'Σημειωσεις'
        ordering = ['-created']
        indexes = [
            models.Index(fields=['user']),
            models.Index(fields=['contact']),]
        
    def __str__(self):
        return f'{self.created.date()} - {self.contact}- {self.status}'
    
    def get_absolute_url(self):
        return reverse('notes:note-update', kwargs={'pk': self.pk})
    
    def has_completed(self):
        if self.status != 'Κλειστό':
            return False
        return True
    
    def generate_shortcode(self):
        last_note = Note.objects.order_by('-created').first()
    
        if last_note and last_note.shortcode and last_note.shortcode.startswith("E-"):
            try:
                last_number = int(last_note.shortcode.split("-")[1])
            except (IndexError, ValueError):
                last_number = 0
        else:
            last_number = 0

        next_number = last_number + 1
        return f"E-00{next_number}"

    def save(self, *args, **kwargs):
        self.completed = self.has_completed()
        if not self.shortcode:
            self.shortcode = self.generate_shortcode()


        super().save(*args, **kwargs)

notes/forms.py
from django import forms
from contact.models import Contact

from .models import Note


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['contact', 'method', 'subject', 'summary', 'status']
        widgets = {
            'contact': forms.Select(attrs={'class': 'form-select input_style'}),
            'method': forms.Select(attrs={'class': 'form-select input_style'}),
            'subject': forms.Select(attrs={'class': 'form-select input_style'}),
            'summary': forms.Textarea(attrs={
                'class': 'form-control input_style',
                'rows': 3,
                'placeholder': 'Πληκτρολογήστε τις σημειώσεις σας εδώ...'
            }),
            'status': forms.Select(attrs={'class': 'form-select input_style'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Accept user in constructor
        super().__init__(*args, **kwargs)
        if user and user.is_authenticated:
            self.fields['contact'].queryset = Contact.objects.owned_by(user)
        else:
            self.fields['contact'].queryset = Contact.objects.none()

notes/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect

from tools.views import NoteFormListView

from .models import Note

   
class NotesIndexView(NoteFormListView):
    
    def get_queryset(self):
        method = self.request.GET.get('method')
        status = self.request.GET.get('status')
        search = self.request.GET.get('search')
        user = self.request.user

        return Note.lookfors.select_related('contact', 'user').filter_notes(
            user=user, method=method, status=status, search=search
            )


    def get_success_url(self):
        return reverse_lazy('notes:index')

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)


class NoteUpdateView(NoteFormListView):
    def dispatch(self, request, *args, **kwargs):
        # self.note_instance = get_object_or_404(Note, pk=self.kwargs['pk'])
        self.note_instance = get_object_or_404(Note.objects.select_related('contact', 'user'),
                                                pk=self.kwargs['pk'])
        if self.note_instance.user != request.user:
            messages.error(request, "Δεν έχετε άδεια να επεξεργαστείτε αυτή τη σημείωση.")
            return redirect('notes:index')
        
        
        
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        method = self.request.GET.get('method')
        status = self.request.GET.get('status')
        search = self.request.GET.get('search')
        return Note.lookfors.filter_notes(
            user=self.request.user,
            method=method,
            contact=self.note_instance.contact,
            status=status,
            search=search
            ).select_related('contact', 'user').order_by('-created')
        
        

    def get_success_url(self):
        return reverse_lazy('notes:note-update', kwargs={'pk': self.note_instance.pk})

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        
        form = self.get_form()
    
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)
    


@login_required
def delete_note(request, pk):
    note = get_object_or_404(Note, pk=pk)
    # Ensure only the owner can delete
    if note.user != request.user:
        messages.error(request, "Δεν έχετε δικαίωμα να διαγράψετε αυτή τη σημείωση.")
        return redirect('notes:index')

    if request.method == 'POST':
        note.delete()
        messages.success(request, "Η σημείωση διαγράφηκε με επιτυχία.")
        return redirect('notes:index')

    messages.warning(request, "Η διαγραφή πρέπει να γίνει μέσω POST αιτήματος.")
    return redirect('notes:index')

templates/notes/create.html
<div class="container container_color shadow p-3  text-darK">               
    <div class="row align-items-center mx-2">
        <div class="col-lg-4">            
            <div class="row ">
                <div class="col mb-3">
                    <ol class="list-group input_style ">
                        {% for item in counts %}

                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                <div class="fw-bold">{{ item.label }}</div>
                            </div>
                            <span class="badge fixed-badge rounded-pill">{{ item.value }}</span>
                        </li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
            <form method="get" 
                class="row g-2 hover-pop bg-gradient formNote_color p-2 ">
                    <div class="col-lg-12">

                        <select class="form-select input_style" name="method" aria-label="Τρόπος Επικοινωνίας">
                            <option value="" {% if not request.GET.method %}selected{% endif %}>Επικοινωνία</option>
                            <option value="Τηλέφωνο" {% if request.GET.method == 'Τηλέφωνο' %}selected{% endif %}>Τηλέφωνο</option>
                            <option value="Γραφείο" {% if request.GET.method == 'Γραφείο' %}selected{% endif %}>Γραφείο</option>
                            <option value="Email" {% if request.GET.method == 'Email' %}selected{% endif %}>Email</option>
                            <option value="Έγγραφο" {% if request.GET.method == 'Έγγραφο' %}selected{% endif %}>Έγγραφο</option>
                            <option value="Άλλο" {% if request.GET.method == 'Άλλο' %}selected{% endif %}>Άλλο</option>
                        </select>
                    </div>
                    <div class="col-lg-12">
                        <select class="form-select input_style" name="status" aria-label="Κατάσταση">
                            <option value="" {% if not request.GET.status %}selected{% endif %}>Κατάσταση</option>
                            <option value="Ανοιχτό" {% if request.GET.status == 'Ανοιχτό' %}selected{% endif %}>Ανοιχτό</option>
                            <option value="Σε Εξέλιξη" {% if request.GET.status == 'Σε Εξέλιξη' %}selected{% endif %}>Σε εξέλιξη</option>
                            <option value="Κλειστό" {% if request.GET.status == 'Κλειστό' %}selected{% endif %}>Κλειστό</option>
                        </select>
                    </div>
                    <div class="col-lg-12">
                        <input
                        class="form-control input_style"
                        type="search"
                        name="search"
                        placeholder="Αναζητηση Επαφής"
                        aria-label="Search"
                        value="{{ request.GET.search|default_if_none:'' }}"
                        />
                    </div>
                    <div class="col-lg-12  mt-3 w-100 text-center">
                        <button type="submit" 
                            class="btn btn-sm filter_color fw-bold">
                            <i class="bi bi-filter"></i>Φιλτράρισμα</button>
                    </div>
                
            </form>

                
        </div>
        <div class="col-lg-8 hover-pop formNote_color bg-gradient">            
            <form method="post" class="row g-3 py-3 mx-3">
                {% csrf_token %}
                <div class="col-md-4">                    
                    <span class="badge label_color mb-2"> {{ form.subject.label_tag }}</span>
                    {{ form.subject }}
                </div>
                <div class="col-md-4">
                    
                    <span class="badge label_color mb-2">{{ form.method.label_tag }} </span>
                    {{ form.method }}
                </div>
                <div class="col-md-4">
                    <span class="badge label_color mb-2">{{ form.status.label_tag }}</span>
                    {{ form.status }}
                </div>
                
                <div class="col-md-6">
                    <span class="badge label_color mb-2">{{ form.contact.label_tag }} </span>
                     {{ form.contact }}                
                </div>
                <div class="col-md-6 pt-4 mt-4">
                    
                    <button type="button" class="btn btn-sm create_color fw-bold bg-gradient"
                            data-bs-toggle="modal" data-bs-target="#contactModal">
                        <i class="bi bi-person-add"></i> Προσθήκη Επαφής
                    </button>
                </div>

                <div class="col-12">
                        <span class="badge label_color mb-2">{{ form.summary.label_tag }} </span>
                        {{ form.summary }}
                </div>
                <div class="col-12 text-center">
                    <button type="submit" class="btn btn fw-bold create_color">
                        <i class="bi bi-clipboard2-plus"></i>
                        {% if note_to_update %}Ανανέωση{% else %}Προσθήκη{%endif%} Σημείωσης
                    </button>
                
                </div>
            </form>
        </div>


    </div>
</div>

templates/notes/header.html
<div class="row">
    <div class="col-8">
        {% if note_to_update %}                  
            <nav class="breadcr" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a   href="#">
                        {{ note_to_update.contact}}</a></li>
                    <li class="breadcrumb-item">
                        {{ note_to_update.created }}</li>

                    <li class="breadcrumb-item" aria-current="page">
                        {{ note_to_update.shortcode }}</li>
                    <li class="breadcrumb-item">
                        {{ note_to_update.updated }}</li>
                </ol>
            </nav>                
        {% endif %}            
    </div>
    <div class="col-4 text-end">
        {% if note_to_update %}
        <form method="post" class="mb-1" 
        action="{% url 'notes:note-delete' note_to_update.pk %}">
            {% csrf_token %}
            <button type="submit" class="btn off_button btn-sm">Διαγραφή</button>
        </form>                        
    {% endif %}
    </div>            
</div>

templates/notes/list.html
{% load note_extras %}
{% load status_state %}

<div class="container-fluid container_color pb-2 mt-3 mb-3 ">
    <div class="row gy-2 shadow-sm p-1 mb-5 rounded ">   
        {% for note in notes %}
            <div class="col-lg-6 col-md-12 col-sm-12  ">
                <div class="card mb-3 h-100 hover-pop formNote_color bg-gradient">
                    <div class="card-body">
                        <div class="row p-2">                    
                            <div class="col-lg-12">                                
                                <h5 class="card-title">                                    
                                    <span class="badge badge-sm {{ note.status|status_clas }} "> </span>
                                    {{ note.contact }}
                                    <em class="status_text">
                                        {{ note.status|safe }}
                                    </em>                                    
                                </h5>                                
                            </div>
                        </div>
                        
                        <h6 class="card-subtitle pb-2">                            
                            
                            <span class="badge bg-gradient p-2 ms-3 label_color ">{{ note.user.first_name }}</span> 
                            <span class="badge p-2 bg-gradient label_color">{{ note.created|date:"d/m/Y H:i" }}</span> 
                            <span class="badge bg-gradient p-2 label_color ">
                                {{ note.subject }}
                            </span>
                            <span class="badge p-2 bg-gradient label_color">
                                {{ note.method }}
                            </span>                            
                            
                            {% if note.user == request.user %}

                                <a class="btn btn-sm m-2 ms-3 
                                detail_color fw-bold bg-gradient"
                                    href="{{ note.get_absolute_url }}">
                                    <i class="bi bi-pencil-square"></i>
                                        <em>{{ note.shortcode }}</em>
                                </a>                    
                                    
                            {% endif %}              
                        </h6>                        
                        <ol class="card-text ">
                            {% for sentence in note.summary|split_sentences %}
                                <li>{{ sentence }}.</li>
                            {% empty %}
                                <em>Χωρίς περίληψη</em>
                            {% endfor %}
                        </ol>                             
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="alert alert-info">Δεν υπάρχουν σημειώσεις.</div>
        {% endfor %}  
    </div>
</div>