config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
        path('', include('notes.urls')),
        path('account/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),
        path('admin/', admin.site.urls),
        path('contact/', include('contact.urls'))
    ]

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + debug_toolbar_urls() 



  

contact/urls.py
from django.urls import path
from .views import create_contact, ContactIndexView, ContactUpdateView

app_name = 'contact'

urlpatterns = [   
    path('', ContactIndexView.as_view(), name='index'),
    path('contact/update/<uuid:pk>/', ContactUpdateView.as_view(), name='contact-update'),
    path('create/', create_contact, name='contact-create'),
    
    ]

notes/urls.py
from django.urls import path
from .views import NotesIndexView, NoteUpdateView, delete_note

app_name = 'notes'

urlpatterns = [
    path('', NotesIndexView.as_view(), name='index'),
    path('note/update/<uuid:pk>/', NoteUpdateView.as_view(), name='note-update'),
    path('note/delete/<uuid:pk>/', delete_note, name='note-delete'),
    ]

contact/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


from tools.constants import TIN_REGEX, PHONE_REGEX, EMAIL_REGEX
from tools.models import TimeStampedModel
from .manager import ContactManager

# Create your models here.
User = get_user_model()

class Contact(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                              verbose_name='Χρήστης', null=True, blank=True)
    first_name = models.CharField('Ονομα', max_length=155)
    last_name = models.CharField('Επίθετο', max_length=155)
    company = models.CharField('Οντότητα', max_length=155, blank=True, null=True)
    email = models.CharField('Email',
                             max_length=200,
                             blank=True,null=True,
                             validators=[EMAIL_REGEX])
    tin_number = models.CharField('ΑΦΜ', max_length=9, blank=True, null=True, 
                                  validators=[TIN_REGEX], unique=True)
    phone_number = models.CharField('Τηεφωνο', max_length=10, blank=True, null=True, validators=[PHONE_REGEX])
    summary = models.TextField('Πληροφορίες', blank=True, null=True)

    objects = ContactManager()
    
    class Meta:
        verbose_name = 'Επαφή'
        verbose_name_plural = 'Επαφές'
        unique_together = ['first_name', 'last_name', 'company', 'user']
        ordering = ['last_name']

    def __str__(self):
        fullname = f'{self.last_name} {self.first_name}'
        display = f'{fullname} - {self.company}' if self.company else fullname
        return display

    def get_absolute_url(self):
        return reverse('contact:contact-update', kwargs={'pk': self.pk})

contact/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            'first_name', 'last_name', 'company', 'email',
            'phone_number', 'tin_number', 'summary'
        ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input',
                                                 'id' :'first_name',
                                                  'placeholder': 'Όνομα'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input', 
                                                'id' :'last_name','placeholder': 'Επίθετο'}),
            'company': forms.TextInput(attrs={'class': 'form-input',
                                              'id' :'company', 'placeholder': 'Εταιρία'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-input',
                                                   'id' :'phone_number', 'placeholder': 'Τηλέφωνο'}),
            'email': forms.TextInput(attrs={'class': 'form-input',
                                            'id' :'email', 'placeholder': 'Email'}),
            'tin_number': forms.TextInput(attrs={'class': 'form-input input_style',
                                                 'id' :'tin_number',
                                                  'placeholder': 'ΑΦΜ'}),
            'summary': forms.Textarea(attrs={'class': 'form-input', 
                                             'id' :'summary',
                                             'rows': 3,
                                             'placeholder': 'Περιγραφή'}),
        }

    def save(self, commit=True, user=None):
        instance = super().save(commit=False)
        if user:
            instance.user = user
        if commit:
            instance.save()
        return instance

contact/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Contact
from .forms import ContactForm
# Create your views here.
@login_required
def create_contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            messages.success(request, 'Η επαφή δημιουργήθηκε με επιτυχία.')
            return redirect('notes:index')
        else:
            for error in form.non_field_errors():
                messages.error(request, error)

            return redirect('notes:index')
    else:
        return redirect('notes:index')
    


class ContactFormListView(LoginRequiredMixin, FormMixin, ListView):

    model = Contact
    template_name = 'contact/index.html' 
    context_object_name = 'contacts'
    paginate_by = 6
    form_class = ContactForm
    contact_instance = None  

    def get_form(self, form_class=None):
        if self.request.method == 'POST':
            return self.form_class(self.request.POST, instance=self.contact_instance)
        return self.form_class(instance=self.contact_instance)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['note_to_update'] = self.contact_instance        
        return context

    def form_valid(self, form):
        is_update = self.contact_instance is not None and self.contact_instance.pk is not None
        contact = form.save(commit=False)
        contact.user = self.request.user
        contact.save()

        if is_update:
            messages.success(self.request, 
                             f'Η επαφή: {contact } ενημερώθηκε με επιτυχία.')
        else:
            messages.success(self.request, 'Η επαφή δημιουργήθηκε με επιτυχία.')

        return super().form_valid(form)


    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

class ContactIndexView(ContactFormListView):
    
    def get_queryset(self):
        search = self.request.GET.get('search')
        user = self.request.user

        return Contact.objects.filter_contacts(
            user=user, search=search)


    def get_success_url(self):
        return reverse_lazy('contact:index')

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)


class ContactUpdateView(ContactFormListView):
    def dispatch(self, request, *args, **kwargs):
        # self.note_instance = get_object_or_404(Note, pk=self.kwargs['pk'])
        self.contact_instance = get_object_or_404(Contact, pk=self.kwargs['pk'])
        if self.contact_instance.user != request.user:
            messages.error(request, "Δεν έχετε άδεια να επεξεργαστείτε αυτή τη επαφή.")
            return redirect('contact:index')     
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        search = self.request.GET.get('search')
        return Contact.objects.filter_contacts(
            user=self.request.user,
            search=search
            )
        
        

    def get_success_url(self):
        return reverse_lazy('contact:cntact-update', kwargs={'pk': self.contact_instance.pk})

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        
        form = self.get_form()
    
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)
    

templates/components/contact_form.html
<div class="modal fade" 
        id="contactModal" 
        data-bs-backdrop="static" 
        data-bs-keyboard="false"
        tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true"
        >
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content" id="contact-modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Δημιουργία Επαφής</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'contact:contact-create' %}">
                    {% csrf_token %}
                    <div class="container">
      
                        <div class="row g-2">
                            <div class="d-grid">
                                {{ form.first_name }}
                                
                            </div>
                            <div class="d-grid">
                                {{ form.last_name }}
                            </div>
                            <div class="d-grid">
                                {{ form.company }}
                            </div>
                            <div class="d-grid">
                                {{ form.phone_number }}
                            </div>
                            <div class="d-grid">
                                {{ form.email }}
                            </div>
                            <div class="d-grid">
                                {{ form.tin_number }}
                            </div>

                            <div class="d-grid">
                                {{ form.summary }}
                            </div>
                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary">Αποθήκευση</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>               
        </div>
    </div>
</div>

templates/components/customer_form.html
<form method="post" action="{% url 'notes:customer-create' %}">
    {% csrf_token %}
      <div class="container">
        
        <div class="row g-2">
            <div class="d-grid">
                {{ form.first_name }}
            </div>
            <div class="d-grid">
                {{ form.last_name }}
            </div>
            <div class="d-grid">
                {{ form.father_name }}
            </div>
            <div class="d-grid">
                {{ form.phone_number }}
            </div>

            <div class="d-grid">
                {{ form.tin_number }}
            </div>

            <div class="d-grid">
                {{ form.summary }}
            </div>
            <div class="d-grid">
                <button type="submit" class="btn btn-primary">Αποθήκευση</button>
            </div>
        </div>
      </div>
</form>

templates/components/footer.html
  <footer class="mt-auto {% if user.is_authenticated %}{% else %}fixed-bottom {% endif %}">
  <div class="container text-dark">
    <div class="row">

      <div class="col-md-12 mb-3 text-center">
        <h5>Follow Us</h5>
        <ul class="list-inline social-icons">
          <li class="list-inline-item"><a href="#" ><i class="bi bi-facebook"></i></a></li>
          <li class="list-inline-item"><a href="#" ><i class="bi bi-youtube"></i></a></li>
          <li class="list-inline-item"><a href="#" ><i class="bi bi-instagram"></i></a></li>
        </ul>
      </div>
    </div>
    <hr class="mb-6">
    <div class="row">
      <div class="col-md-12 text-center">
        <p>&copy; 2025 steriospydev. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

templates/components/messages.html
{% if messages %}  
    <div class="messages">
        <div class="alert alert-success alert-dismissible fade show "
            role="alert">
            <ul>
                {% for message in messages %}
                <li class="{{ message.tags}}">                                       
                    {{ message }}
                </li>
                {% endfor %}
            </ul>            
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>         
    </div>
{% endif %}

templates/components/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-gradient navbar_color">
  <div class="container p-2">
    <a class="navbar-brand d-flex navbar_link align-items-center" href="{% url 'notes:index' %}">
      <img src="{% static 'images/logo.png' %}"
       alt="" width="60" height="34"
       class="d-inline-block align-text-top rounded me-2 rounded-circle">
      {% if user.is_authenticated %}{{user.first_name}} {{ user.last_name}}{% else %}CRM{% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mx-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link navbar_link {% if request.path == '/' %}active{% endif %}" aria-current="page" 
          href="{% url 'notes:index' %}">Σημειώσεις</a>
        </li>
        <li class="nav-item">
          <a class="nav-link  navbar_link" href="{% url 'contact:index' %}">Επαφές</a>
        </li>       
          
        {% endif %}
      </ul>
        {% if user.is_authenticated %}
     
          <form method="post" action="{% url 'logout' %}">
             {% csrf_token %}
             <button type="submit" class="btn off_button fw-bold bg-gradient">
              <i class="bi bi-power"></i>Έξοδος</button>
          </form>
        
        {% endif %}

    </div>
  </div>
</nav>